### ISSUE TITLE
Sensitive data committed

### ISSUE THREAD

**Issue by EHER** [CajuCLC/ansible-rax-magento-lamp-db#1]
Maybe that data should be store in [Vault](http://docs.ansible.com/playbooks_vault.html) or [Password Lookup](http://docs.ansible.com/playbooks_lookups.html#the-password-lookup)
https://github.com/CajuCLC/ansible-rax-magento-lamp-db/blob/master/rax.py#L2-L3

If that information is really important, you can [ask github to remove](https://help.github.com/articles/remove-sensitive-data). Of course you should consider the data to be compromised.

**Comment by CajuCLC** [comment]
It was a mistake I made. It should be without the user and key.
There is the need to inform your username and API Key from Rackspace.
